version: "3.3"

networks:
  projet:

volumes:
  db:

services:
  pma:
    image: phpmyadmin
    networks: [projet]
    depends_on: [mysql]
    ports: ["8000:80"]
    environment:
      - PMA_HOST=mysql

  mysql:
    image: mysql:5.7
    networks: [projet]
    ports: ["3307:3306"]
    volumes: ["db:/var/lib/mysql"]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops

  # frontend:
  #   image: FIXME
  #   networks: [projet]
  #   depends_on: [backend]
  #   ports: ["80:80"]

  backend:
    build: .
    image: devops/backend
    networks: [projet]
    depends_on: [mysql]
    ports: ["3000:3000"]
    environment:
      - SERVER_PORT=3000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/devops?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root